server:
  # 服务端口号
  port: 8765
spring:
  profiles: service-feign
  application:
    # 服务名，即serviceId
    name: service-feign
eureka:
  client:
    serviceUrl:
      # 安全认证的服务注册中心地址
      defaultZone: http://localhost:8761/eureka

# 熔断器设置
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---

server:
  # 服务端口号
  port: 8766
spring:
  profiles: service-feign-2
  application:
    # 服务名，即serviceId
    name: service-feign-2
eureka:
  client:
    serviceUrl:
      # 安全认证的服务注册中心地址
      defaultZone: http://localhost:8761/eureka

# 熔断器设置
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"